name: emailvalidator
description: A simple (but correct) dart class for validating email addresses
version: 0.1.0
author: Fredrik Eilertsen <fredrik.eilertsen@gmail.com>
homepage: https://github.com/fredeil/EmailValidation
dependencies:
  test: ^1.3.0
executables:
environment: