name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version: git tag and package version you want create (sample 1.0.0)"
        required: true
      dry_run:
        description: "dry_run: true will never publish the release."
        required: true
        default: "false"

env:
  GIT_TAG: ${{ github.event.inputs.tag }}
  DRY_RUN: ${{ github.event.inputs.dry_run }}

jobs:

  publish:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.commit.outputs.sha }}
      branch-name: ${{ steps.env.outputs.branch-name }}

    steps:
      - name: Configure Environment Variables
        id: env
        run: |
          echo "FILE_PATH=pubspec.yaml" | tee -a "$GITHUB_ENV"
          echo "GIT_TAG=${{ inputs.tag }}" | tee -a "$GITHUB_ENV"
          echo "DRY_RUN=${{ inputs.dry-run }}" | tee -a "$GITHUB_ENV"
          echo "::set-output name=branch-name::${{ env.DRY_RUN_BRANCH_PREFIX }}-${{ inputs.tag }}"
      
      - uses: actions/checkout@v3

      - name: Output pubspec.yaml (Before)
        run: cat ${{ env.FILE_PATH}}

      - name: Update pubspec.yaml to version ${{ env.GIT_TAG }}
        run: sed -i -e 's/^\(\s*version\s*:\s*\).*/\1 ${{ env.GIT_TAG }}/' ${{ env.FILE_PATH }}

      - name: Check update
        id: check_update
        run: |
          cat ${{ env.FILE_PATH}}
          git diff --exit-code || echo "::set-output name=changed::1"

      - name: Commit files
        id: commit
        if: steps.check_update.outputs.changed == '1'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pubspec.yaml
          git commit -m "feat: Update pubspec.yaml to ${{ env.GIT_TAG }}"
          echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Check sha
        run: echo "SHA ${SHA}"
        env:
          SHA: ${{ steps.commit.outputs.sha }}

      - name: Create Tag
        if: steps.check_update.outputs.changed == '1'
        run: git tag ${{ env.GIT_TAG }}

      - name: Push changes
        if: env.DRY_RUN == 'false' && steps.check_update.outputs.changed == '1'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Push changes (dry_run)
        if: env.DRY_RUN == 'true' && steps.check_update.outputs.changed == '1'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.env.outputs.branch-name }}
          tags: false

      - name: Publish release
        if: env.DRY_RUN == 'false' && steps.check_update.outputs.changed == '1'
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIALS }}
          skip_test: true
          dry_run: false

      - name: Publish release (dry-run)
        if: env.DRY_RUN == 'true' && steps.check_update.outputs.changed == '1'
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          credential: ${{ secrets.CREDENTIALS }}
          skip_test: true
          dry_run: true



